[metadata]
name = asyncio-atexit
version = attr: asyncio_atexit.__version__
description = Like atexit, but for asyncio
long_description = file: README.md
long_description_content_type = text/markdown
author = Min RK
author_email = benjaminrk@gmail.com
url = https://github.com/minrk/asyncio-atexit
keywords = asyncio
license = MIT License
classifiers =
    Framework :: AsyncIO
    License :: OSI Approved :: MIT License
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.6
    Programming Language :: Python :: 3.7
    Programming Language :: Python :: 3.8
    Programming Language :: Python :: 3.9
    Programming Language :: Python :: 3.10
    Programming Language :: Python :: 3.11
    Programming Language :: Python :: 3.12
    Programming Language :: Python :: 3.13
    Programming Language :: Python :: 3.14

[options]
py_modules = asyncio_atexit
python_requires = >=3.6

[options.extras_require]
test =
    pytest; python_version >= "3.7"
    pytest < 7; python_version < "3.7"
    uvloop; python_version >= "3.7"
    uvloop == 0.14.0; python_version < "3.7"

[tool:pytest]
# asyncio_mode = auto
filterwarnings =
    error::DeprecationWarning
