# This is a GitHub workflow defining a set of jobs with a set of steps.
# ref: https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions
#
name: Tests

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  # Run tests
  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 10

    strategy:
      # Keep running even if one variation of the job fail
      fail-fast: false
      matrix:
        python:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"

    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Install Python ${{ matrix.python }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python }}
          cache: pip
          cache-dependency-path: dev-requirements.txt

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install --upgrade .[test] -r dev-requirements.txt
          pip freeze

      - name: Run tests
        # FIXME: --color=yes explicitly set because:
        #        https://github.com/actions/runner/issues/241
        run: |
          pytest -v --color=yes --cov=asyncio_atexit

      - name: Submit codecov report
        run: |
          codecov

  test-python-36:
    runs-on: ubuntu-22.04
    container: python:3.6.15-slim-buster
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade .[test] -r dev-requirements.txt
          python -m pip freeze

      - name: Run tests
        run: |
          python -m pytest -v --color=yes --cov=asyncio_atexit

      - name: Submit codecov report
        run: |
          codecov
